include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# =============================================================================
# ENVIRONMENT TESTS
# =============================================================================

environment tests for test env post-deploy:
  stage: post-deploy environment tests
  interruptible: false
  resource_group: test
  variables:
    CLERK_SECRET_KEY: "${CLERK_SECRET_KEY_DEVELOPMENT}"
    INTEGRATION_TEST_CLIENT_DOMAIN: "test.scratch.md"
    INTEGRATION_TEST_API_DOMAIN: "test-api.scratch.md"
    INTEGRATION_TEST_USER_ID: user_35RRk1ww8PJ4g0TfVfxbeU5iFJz
  script:
    - cd server
    - !reference [.use_nvm, script]
    - yarn run test:integration --verbose --reporters=default --reporters=jest-junit
  cache: !reference [.caches, server]
  dependencies: []
  artifacts:
    when: always
    reports:
      junit: "server/junit.xml"
  rules:
    # - !reference [.rules, on_merge_to_master]
    - when: never

environment tests for test env pre-deploy:
  stage: pre-deploy environment tests
  interruptible: false
  resource_group: test
  variables:
    CLERK_SECRET_KEY: "${CLERK_SECRET_KEY_DEVELOPMENT}"
    INTEGRATION_TEST_CLIENT_DOMAIN: "test.scratch.md"
    INTEGRATION_TEST_API_DOMAIN: "test-api.scratch.md"
    INTEGRATION_TEST_USER_ID: user_35RRk1ww8PJ4g0TfVfxbeU5iFJz
  script:
    - cd server
    - !reference [.use_nvm, script]
    - yarn run test:integration --verbose --reporters=default --reporters=jest-junit
  cache: !reference [.caches, server]
  artifacts:
    when: always
    reports:
      junit: "server/junit.xml"
  rules:
    # - !reference [.rules, on_merge_to_prod]
    - when: never
# notify slack on environment test failure test env post-deploy:
#   stage: post-deploy environment tests
#   needs:
#     - environment tests for test env post-deploy
#   dependencies: []
#   script:
#     - |
#       curl -X POST -H 'Content-type: application/json' \
#       --data "{\"text\":\"❌ Integration tests for Scratch failed - Test\n<${CI_PIPELINE_URL}|View Pipeline>\"}" \
#       ${SLACK_SCRATCH_TEST_FEED_WEBHOOK_URL}
#   rules:
#     - !reference [.rules, on_merge_to_master]
#   when: on_failure

# notify slack on environment test failure test env pre-deploy:
#   stage: pre-deploy environment tests
#   needs:
#     - environment tests for test env pre-deploy
#   dependencies: []
#   script:
#     - |
#       curl -X POST -H 'Content-type: application/json' \
#       --data "{\"text\":\"❌ Integration tests for Scratch failed - Test\n<${CI_PIPELINE_URL}|View Pipeline>\"}" \
#       ${SLACK_SCRATCH_PROD_FEED_WEBHOOK_URL}
#   rules:
#     - !reference [.rules, on_merge_to_prod]
#   when: on_failure
